name: Lint and Validate

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    uses: garemat/moonstone-companion-data/.github/workflows/validate.yml@main
    with:
      pr_body: ${{ github.event.pull_request.body }}
